language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# command to install dependencies
install:
# command to run tests
script: cd tests && python -m unittest discover
